spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: root
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/book?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
      username: root
      password: root
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 30000
  redis:
    database: 2
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
    timeout: 100ms
  zipkin:
    base-url:  http://127.0.0.1:9411/

info:
  name: oauth2
  server:
    port: ${server.port}
